# このファイルはシンボリックリンクせずにコピペして使う。
# 実行環境ごとにプロジェクトの信頼設定などが書き込まれるため。

# model_reasoning_effort = "high" # gpt-5-codex では指定しない方が良い結果になるらしい
hide_agent_reasoning = true
network_access = true

notify = ["bash", "-lc", "afplay /System/Library/Sounds/Ping.aiff"]

[tools]
web_search = true

[mcp_servers.shadcn]
command = "bunx"
args = ["--bun", "shadcn@latest", "mcp"]

[mcp_servers.serena]
command = "uvx"
args = [
  "--from",
  "git+https://github.com/oraios/serena",
  "serena",
  "start-mcp-server",
  "--context",
  "codex",
]

[mcp_servers.chrome-devtools]
command = "bunx"
args = ["--bun", "chrome-devtools-mcp@latest"]
