[hooks]
enter = "mise tasks run setup"

[tools]
"github:dyoshikawa/rulesync" = "latest"

[tasks.setup]
run = [
    "mise install",
    "GH_TOKEN=$(gh auth token) rulesync install",
    "rulesync generate",
    # pstack でハーネスごとにモデルの参照箇所を書き換える
    "sed -i '' 's@~/.cursor/rules/pstack-models.mdc@~/.gemini/antigravity-cli/skills/pstack-mod/SKILL.md@g' ~/.gemini/antigravity-cli/skills/arena/SKILL.md",
    "sed -i '' 's@~/.cursor/rules/pstack-models.mdc@~/.agents/skills/pstack-mod/SKILL.md@g' ~/.agents/skills/arena/SKILL.md",
]

[tasks.update-skills]
run = [
    "GH_TOKEN=$(gh auth token) rulesync install --update",
]
