###########################################################
# Basics
###########################################################
set -g mouse on

###########################################################
# Key bindings
###########################################################
# hjkl で pane 移動
bind -r h select-pane -L
bind -r j select-pane -D
bind -r k select-pane -U
bind -r l select-pane -R
# HJKL で pane リサイズ
bind -r H resize-pane -L 5
bind -r J resize-pane -D
bind -r K resize-pane -U
bind -r L resize-pane -R 5
# 1234 で layout 変更
bind 1 select-layout even-horizontal
bind 2 select-layout tiled
bind 3 select-layout main-vertical
bind 4 select-layout main-vertical-mirrored

###########################################################
# For pi-coding-agent (Shift+Enterなどが pi on tmux で動作するように)
###########################################################
set -g extended-keys on
set -g extended-keys-format csi-u
