[tools]
# languages
bun = "latest"
node = "lts"
rust = "latest"
python = "latest"
# あまり利用していないのでコメントアウトする
# 必要になったらば、コメントアウトを外してインストールする。
# deno = "latest"
# go = "latest"
# ruby = "4.0"

# PHP 以下のコマンドでインストールする必要があるが、それでもトラブるから mise で管理しない
# HP_CONFIGURE_OPTIONS="--with-openssl=$(brew --prefix openssl) --with-iconv=$(brew --prefix libiconv)" mise install
# see: https://github.com/asdf-community/asdf-php/issues/163#issuecomment-2518719651
# php = "8.5"

# tools
uv = "latest"
terraform = "latest"
# "github:pocketbase/pocketbase" = "latest"

# packages
"npm:pnpm" = "latest"
"npm:yarn" = "1.22.22"
"npm:serve" = "latest"
"npm:@biomejs/biome" = "latest"
"npm:@github/copilot" = "latest"
"npm:@playwright/cli" = "latest"
"npm:@earendil-works/pi-coding-agent" = "latest"
"npm:@anthropic-ai/sandbox-runtime" = "latest"

[settings]
python.uv_venv_auto = "create|source" # .venv がなければ作成して有効化
